spring.application.name=escalaSimplex

spring.datasource.url=jdbc:postgresql://localhost:5431/escalas_db?sslmode=disable
spring.datasource.username=escalas_user
spring.datasource.password=escalas_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true